import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../assets/logo.png'
import 'swiper/css'
import 'swiper/css/autoplay'
import 'swiper/css/pagination'

import { Swiper, SwiperSlide } from 'swiper/react'
import { Pagination, Autoplay } from 'swiper'

import { FaWhatsapp } from 'react-icons/fa'

export default function Home() {
	const clickHandlerNewTab = (url) => {
		window.open(url, '_blank', 'noopener,noreferrer')
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header className={styles.header}>
				<Image src={logo} width={150} height={150} />

				<h1 className={styles.title}>
					<a href='https://www.instagram.com/reabilityodontoclinic/'>
						Reability Odontoclinic
					</a>
				</h1>
			</header>
			<main className={styles.main}>
				<p className={styles.description}>
					{/* <code className={styles.code}>pages/index.js</code> */}
				</p>

				<Swiper
					className={styles.grid}
					pagination={{
						dynamicBullets: true,
						horizontalClass: styles.pagination,
						dynamicBulletsClass: styles.dynamicBullets,
					}}
					modules={[Pagination, Autoplay]}
					spaceBetween={20}
					slidesPerView={'auto'}
					autoplay={true}
					loop={true}
				>
					<SwiperSlide>
						<div className={styles.card}>
							<code>Pacote</code>

							<h2> Diagnóstico com saúde </h2>

							<p>✓ Questionário de saúde</p>
							<p>✓ Consulta inicial</p>
							<p>✓ Avaliação periodontial</p>
							<p>✓ Tratamento periodontal inicial</p>
							<p>✓ Revitalização de restaurações</p>
							<p>✓ Planejamento do tratamento</p>
							<p>
								✓ Diagnóstico radiográfico intra-oral completo
							</p>
							<button
								className={styles.button}
								onClick={() =>
									clickHandlerNewTab('https://api.whatsapp.com/send/?phone=%2B5571993586357&text=Quero+agendar+minha+consulta+de+avalia%C3%A7%C3%A3o+com+o+pacote+de+diagnóstico+com+saúde.&type=phone_number&app_absent=0')
								}
							>
								<FaWhatsapp />
								Agende já sua avaliação
								<FaWhatsapp />
							</button>
						</div>
					</SwiperSlide>
					<SwiperSlide>
						<div
							href='https://nextjs.org/learn'
							className={styles.card}
						>
							<code>Pacote</code>

							<h2>Saúde total </h2>
							<p>
								✓ Indispensável &quot;Diagnóstico em saúde&quot;
							</p>
							<p>✓ Extrações dentárias</p>
							<p>✓ Tratamento periodontal avançado</p>
							<button
								className={styles.button}
								onClick={() =>
									clickHandlerNewTab('https://api.whatsapp.com/send/?phone=%2B5571993586357&text=Quero+agendar+minha+consulta+com+o+pacote+de+saúde+total.&type=phone_number&app_absent=0')
								}
							>
								<FaWhatsapp />
								Garanta já seu pacote
								<FaWhatsapp />
							</button>
						</div>
					</SwiperSlide>
					<SwiperSlide>
						<div className={styles.card}>
							<code>Pacote</code>

							<h2>Reabilitaçao básica </h2>
							<p>
								✓ Indispensável &quot;Diagnóstico em saúde&quot;
							</p>
							<p>✓ Restaurações / obturações não estéticas</p>
							<p>✓ Endodontia</p>
							<p>✓ Urgência</p>
							<button
								className={styles.button}
								onClick={() =>
									clickHandlerNewTab('https://api.whatsapp.com/send/?phone=%2B5571993586357&text=Quero+agendar+minha+consulta+de+avalia%C3%A7%C3%A3o+com+o+pacote+de+reabilitação+básica.&type=phone_number&app_absent=0')
								}
							>
								<FaWhatsapp />
								Vamos reabilitar?
								<FaWhatsapp />
							</button>
						</div>
					</SwiperSlide>
					<SwiperSlide>
						<div className={styles.card}>
							<code>Pacote</code>

							<h2>Reabilitaçao avançada </h2>
							<p>
								✓ Indispensável &quot;Diagnóstico em saúde&quot;
							</p>
							<p>
								✓ Indispensável &quot;Reabilitaçao básica&quot;
							</p>
							<p>✓ Implantes unitario</p>
							<button
								className={styles.button}
								onClick={() =>
									clickHandlerNewTab('https://api.whatsapp.com/send/?phone=%2B5571993586357&text=Quero+agendar+minha+consulta+de+avalia%C3%A7%C3%A3o+com+o+pacote+de+reabilitação+avançada.&type=phone_number&app_absent=0')
								}
							>
								<FaWhatsapp />
								Garanta o melhor
								<FaWhatsapp />
							</button>
						</div>
					</SwiperSlide>
					<SwiperSlide>
						<div className={styles.card}>
							<code>Pacote</code>
							<h2>Reabilitaçao total</h2>
							<p>
								✓ Indispensável &quot;Diagnóstico em saúde&quot;
							</p>
							<p>
								✓ Indispensável &quot;Reabilitaçao básica&quot;
							</p>
							<p>✓ Implantes em protocolo</p>
							<button
								className={styles.button}
                onClick={() =>
									clickHandlerNewTab('https://api.whatsapp.com/send/?phone=%2B5571993586357&text=Quero+agendar+minha+consulta+de+avalia%C3%A7%C3%A3o+com+o+pacote+de+reabilitação+total.&type=phone_number&app_absent=0')
								}
							>
								<FaWhatsapp />
								Sua transformação total
								<FaWhatsapp />
							</button>
						</div>
					</SwiperSlide>
				</Swiper>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	)
}
